# Generated by Django 5.0 on 2024-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieapi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('retting', models.CharField(max_length=10)),
            ],
        ),
    ]
